# Generated by Django 4.1 on 2022-08-10 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='verifeid_email',
            new_name='verified_email',
        ),
    ]
