# Generated by Django 4.1 on 2022-08-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_verifeid_email_customuser_verified_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='verification_email_secret',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
