# Generated by Django 4.1 on 2022-08-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customuser_verification_email_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reset_password_secret',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
